
name: Deploy Bunny Scripting Script

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  update-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install
        run: "npm install"

      - name: Build
        run: "npm run build"

      - name: Publish the script to Bunny
        uses: "BunnyWay/actions/deploy-script@main"
        with:
          script_id: 63606
          file: "gunicorn --bind 0.0.0.0:8001 --workers 1 --threads 4 --timeout 60 wsgi:flask_app"
